%**************************************************************************
%Programa para análise linear de estruturas reticuladas em regime elast.
%linear usando M.E.F. (ALERMEF)
%Autora: RAFAELA BERNARDES RABELO
%Versão de: 28/12/2020
%**************************************************************************

function [defor,tens] = ALERMEF_EP_RQ8_DeformacoesTensoes(E,nu,a,b,uel,...
    tipoestr)
%0,0 local
x=0;y=0;
Be = zeros(3,8);
Be = [((a * b * y - a * y ^ 2 + 2 * b ^ 2 * x - 2 * b * x * y) / a ^ 2 /...
b ^ 2) / 0.4e1 0 -((a * b * y - a * y ^ 2 - 2 * b ^ 2 * x + 2 * b * x ...
* y) / a ^ 2 / b ^ 2) / 0.4e1 0 ((a * b * y + a * y ^ 2 + 2 * b ^ 2 *...
x + 2 * b * x * y) / a ^ 2 / b ^ 2) / 0.4e1 0 -((a * b * y + a * y ^ 2 -...
2 * b ^ 2 * x - 2 * b * x * y) / a ^ 2 / b ^ 2) / 0.4e1 0 -x * (b - y) / ...
a ^ 2 / b 0 ((b ^ 2 - y ^ 2) / a / b ^ 2) / 0.2e1 0 -x * (b + y) / a ^ 2 /...
b 0 -((b ^ 2 - y ^ 2) / a / b ^ 2) / 0.2e1 0; 0 ((2 * a ^ 2 * y + a * b * x...
- 2 * a * x * y - b * x ^ 2) / a ^ 2 / b ^ 2) / 0.4e1 0 ((2 * a ^ 2 * y - ...
a * b * x + 2 * a * x * y - b * x ^ 2) / a ^ 2 / b ^ 2) / 0.4e1 0 ((2 * ...
a ^ 2 * y + a * b * x + 2 * a * x * y + b * x ^ 2) / a ^ 2 / b ^ 2) /...
0.4e1 0 ((2 * a ^ 2 * y - a * b * x - 2 * a * x * y + b * x ^ 2) / a ^ 2 /...
b ^ 2) / 0.4e1 0 -((a ^ 2 - x ^ 2) / a ^ 2 / b) / 0.2e1 0 -y * (a + x) /...
a / b ^ 2 0 ((a ^ 2 - x ^ 2) / a ^ 2 / b) / 0.2e1 0 -y * (a - x) / a / ...
b ^ 2; ((2 * a ^ 2 * y + a * b * x - 2 * a * x * y - b * x ^ 2) / a ^ 2 /...
b ^ 2) / 0.4e1 ((a * b * y - a * y ^ 2 + 2 * b ^ 2 * x - 2 * b * x * y) / ...
a ^ 2 / b ^ 2) / 0.4e1 ((2 * a ^ 2 * y - a * b * x + 2 * a * x *...
y - b * x ^ 2) / a ^ 2 / b ^ 2) / 0.4e1 -((a * b * y - a * y ^ 2 - 2 *...
b ^ 2 * x + 2 * b * x * y) / a ^ 2 / b ^ 2) / 0.4e1 ((2 * a ^ 2 * y + a * ...
b * x + 2 * a * x * y + b * x ^ 2) / a ^ 2 / b ^ 2) / 0.4e1 ((a * b * y + ...
a * y ^ 2 + 2 * b ^ 2 * x + 2 * b * x * y) / a ^ 2 / b ^ 2) / 0.4e1 ...
((2 * a ^ 2 * y - a * b * x - 2 * a * x * y + b * x ^ 2) / a ^ 2 / b ^ 2) ...
/ 0.4e1 -((a * b * y + a * y ^ 2 - 2 * b ^ 2 * x - 2 * b * x * y) / a ^ 2 /...
b ^ 2) / 0.4e1 -((a ^ 2 - x ^ 2) / a ^ 2 / b) / 0.2e1 -x * (b - y) / a ^ 2 / ...
b -y * (a + x) / a / b ^ 2 ((b ^ 2 - y ^ 2) / a / b ^ 2) / 0.2e1 ...
((a ^ 2 - x ^ 2) / a ^ 2 / b) / 0.2e1 -x * (b + y) / a ^ 2 / b -y * (a - x) /...
a / b ^ 2 -((b ^ 2 - y ^ 2) / a / b ^ 2) / 0.2e1;];
defor = Be*uel;
    if strcmp(tipoestr,'EPD')
        E=E/(1-nu^2);
        nu= nu/(1-nu);
    end
Ee = zeros(3,3);
Ee(1,1)= 1;Ee(1,2)= nu;
Ee(2,1)= nu;Ee(2,2)= 1;
Ee(3,3)= (1-nu)*(1/2);
Ee= (E/(1-nu^2))*Ee;
tens = Ee*defor;
end

